### ISSUE TITLE
Implement in-memory database

### ISSUE THREAD

**Issue by Noroth** [eurofurence/reg-room-service#36]
We would like to have an in-memory database for unit testing.
There should be already existing libraries for that. We shouldn't implement our own logic.

AC:
* Check if there are suitable test libraries for using in-memory databases. which are capable of using MySQL syntax
* If there is nothing suitable for us, we should implement it like it is in other services

**Comment by Jumpy-Squirrel** [comment]
After some research, I'll try https://github.com/dolthub/go-mysql-server first. Just from the docs, it sounds good, and seems maintained ok.

**Comment by Jumpy-Squirrel** [comment]
Tried it. Not convincing.

- devs will need to manage a port for the inmem db
- local compile time increases by factor of 6
- action runtime for the build increases by factor of 10 to over 1 minute

Scrapping this.
