### ISSUE TITLE
Decide about logging call style format

### ISSUE THREAD

**Issue by Noroth** [eurofurence/reg-room-service#38]
I checked. Back when I introduced go-autumn-logging, I didn't go through the entire code to update every place where the logging Wrapper was called, because the logging wrapper was also passed around as a function argument, and that would have meant bigger code changes. We knew we'd be reworking all the services anyway.

But now that time has come :)

While I don't mind a wrapper if it helps us, autumn logging already includes very similar convenience functions, which will look up the request logger in the context, meaning all log lines will have trace ids set etc.

See https://github.com/StephanHCB/go-autumn-logging/blob/master/convenience.go

We should decide whether we want to use
- a wrapper
- autumn convenience.go callstyle
- autumn object callstyle (same style as zerolog)
and then stick to it across our codebase.

_Originally posted by @Jumpy-Squirrel in https://github.com/eurofurence/reg-room-service/pull/37#discussion_r1285247350_

**Comment by Jumpy-Squirrel** [comment]
Just to document the decision:

We picked autumn convenience.go callstyle.

For an example, see the database implementation on mainline.
